@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Add a new user
POST {{baseUrl}}/api/users HTTP/1.1
Content-Type: application/json

{
  "image": "#",
  "email": "dogfan@wuff.de",
  "password": "123",
  "firstName": "Steffi",
  "lastName": "Dogmum",
  "streetName": "Townstreet",
  "postcode": 50000,
  "city": "Köln",
  "docs": "#",
  "dogs": [
    {
      "dogName": "Susi",
      "sex": "female",
      "dateOfBirth": 26,
      "breed": "Mixed",
      "size": 54,
      "weight": 17
    }
  ];
}

### Request all users
GET {{baseUrl}}/api/users HTTP/1.1
Accept: application/json