@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}

### Add a new user
POST {{baseUrl}}/api/users HTTP/1.1
Content-Type: application/json

{
  "image": "#",
  "email": "dogfan@dogmail.com",
  "password": "superDog9000",
  "firstName": "Susi",
  "lastName": "Arglos",
  "streetName": "Dog Avenue",
  "postcode": 50000,
  "city": "Dogtown",
  "docs": "#"
}

### Request all users
GET {{baseUrl}}/api/users HTTP/1.1
Accept: application/json